# 1. Imports

In [1]:
import subprocess
import pandas as pd

# 2. Ejecución

In [2]:
subprocess.run(['python', '-m', 'scripts.label_dataset'], check=True)

Loading Spain dataframe
Calculating thresholds for Spain
Labeling Spain rows
Saving Spain dataset
Cleaning Spain objects
Loading CLM dataframe
Calculating CLM thresholds
Labeling CLM rows
Saving CLM dataset
Cleaning CLM objects
Done

CompletedProcess(args=['python', '-m', 'scripts.label_dataset'], returncode=0)

# 3. Comprobación

In [3]:
from dataset_labeling.config import MODE
if MODE == 'global':
    cols = [
        'extreme_tmax',
        'extreme_tmin',
        'extreme_prec',
        'extreme_racha',
        'extreme_velmedia',
        'extreme_tmax_global',
        'extreme_tmin_global',
        'extreme_prec_global',
        'extreme_racha_global',
        'extreme_velmedia_global',
    ]
else:
    cols = [
    'extreme_tmax',
    'extreme_tmin',
    'extreme_prec',
    'extreme_racha',
    'extreme_velmedia',
]

In [4]:
df = pd.read_parquet('datasets/parquet/LABELED_CURATED_AEMET.parquet')
df[cols].describe()

       extreme_tmax extreme_tmin extreme_prec extreme_racha extreme_velmedia
count        797485       797298       762512        787871           792692
unique            2            2            2             2                2
top           False        False        False         False            False
freq         747450       758847       724990        747918           754142

In [5]:
df[['velmedia_threshold', 'racha_threshold', 'extreme_tmax', 'extreme_tmin', 'extreme_prec']].isna().sum().to_list()

[0, 0, 1853, 2040, 36826]

In [6]:
df.describe()

,fecha,tmed,tmax,tmin,velmedia,racha,hrMedia,prec,presMax,presMin,...,latitud,presMedia,mslp_media,mslp_max,mslp_min,tmax_threshold,tmin_threshold,prec_threshold,velmedia_threshold,racha_threshold
count,799338,797261.000000,797485.000000,797298.000000,792692.000000,787871.000000,792983.000000,762512.000000,793118.000000,793099.000000,...,799338.000000,793051.000000,792115.000000,792164.000000,792149.000000,799338.000000,799338.000000,799338.000000,799338.000000,799338.000000
mean,2008-01-05 22:42:10.968376576,17.024326,21.991316,12.057722,3.458998,10.238269,65.677109,1.586203,993.569031,989.286499,...,38.489441,991.428040,1017.587219,1019.787720,1015.386841,26.923910,7.831472,8.431881,6.418622,16.589823
min,1990-01-01 00:00:00,-10.700000,-5.800000,-17.000000,0.000000,0.000000,5.000000,0.000000,904.900024,895.400024,...,27.818890,900.150024,944.935486,946.541260,943.329651,11.480000,-7.920000,0.000000,2.515000,9.910000
25%,1999-05-25 00:00:00,12.200000,16.700001,7.400000,1.900000,7.500000,55.000000,0.000000,969.000000,964.400024,...,37.190277,966.750000,1013.711060,1015.870239,1011.461304,21.840000,2.170000,2.380000,4.940000,14.440000
50%,2008-05-14 00:00:00,17.200001,21.799999,12.400000,3.100000,9.700000,67.000000,0.000000,1007.700012,1003.099976,...,39.560833,1005.449951,1017.282166,1019.307678,1015.326721,26.585001,8.020000,6.900000,6.100000,16.340000
75%,2016-09-12 00:00:00,22.000000,27.000000,17.000000,4.400000,12.500000,77.000000,0.100000,1015.599976,1011.799988,...,41.640556,1013.699951,1021.397583,1023.495239,1019.493286,31.799999,13.420000,12.115001,7.515000,18.299999
max,2024-12-31 00:00:00,37.200001,47.000000,33.200001,21.100000,47.799999,100.000000,270.200012,1043.000000,1039.800049,...,43.566944,1041.400024,1048.111816,1049.684082,1046.539429,42.900002,22.400000,52.699997,15.000000,30.720001
std,NaN,6.439497,7.173942,6.419298,2.133850,3.968649,15.921958,5.708971,28.843946,29.046795,...,4.583237,28.917391,6.502665,6.269444,6.976344,6.476813,6.804071,7.664376,2.072181,2.843996

In [7]:
df[df['tmax'] == df['tmax'].max()]

,fecha,indicativo,nombre,provincia,tmed,tmax,tmin,velmedia,racha,hrMedia,...,tmax_threshold,tmin_threshold,prec_threshold,velmedia_threshold,racha_threshold,extreme_tmax,extreme_tmin,extreme_prec,extreme_velmedia,extreme_racha
718102,2021-08-15,7228,"ALCANTARILLA, BASE AÉREA",MURCIA,34.599998,47.0,22.299999,3.9,16.4,35.0,...,38.919998,17.82,0.995,4.36,13.01,True,False,False,False,True

In [8]:
df[df['tmin'] == df['tmin'].max()]

,fecha,indicativo,nombre,provincia,tmed,tmax,tmin,velmedia,racha,hrMedia,...,tmax_threshold,tmin_threshold,prec_threshold,velmedia_threshold,racha_threshold,extreme_tmax,extreme_tmin,extreme_prec,extreme_velmedia,extreme_racha
246709,2001-07-31,6325O,ALMERÍA AEROPUERTO,ALMERIA,36.200001,39.200001,33.200001,12.8,21.1,18.0,...,37.02,20.120001,0.0,8.1,16.82,True,False,False,True,True

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 799338 entries, 0 to 799337
Data columns (total 34 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   fecha               799338 non-null  datetime64[ns]
 1   indicativo          799338 non-null  category
 2   nombre              799338 non-null  category
 3   provincia           799338 non-null  category
 4   tmed                797261 non-null  float32
 5   tmax                797485 non-null  float32
 6   tmin                797298 non-null  float32
 7   velmedia            792692 non-null  float32
 8   racha               787871 non-null  float32
 9   hrMedia             792983 non-null  float32
 10  prec                762512 non-null  float32
 11  presMax             793118 non-null  float32
 12  presMin             793099 non-null  float32
 13  anio                799338 non-null  int16
 14  mes                 799338 non-null  int8
 15  dia                 799338 non-null  int8
 16  diaAnio             799338 non-null  int16
 17  altitud             799338 non-null  int16
 18  longitud            799338 non-null  float32
 19  latitud             799338 non-null  float32
 20  presMedia           793051 non-null  float32
 21  mslp_media          792115 non-null  float32
 22  mslp_max            792164 non-null  float32
 23  mslp_min            792149 non-null  float32
 24  tmax_threshold      799338 non-null  float32
 25  tmin_threshold      799338 non-null  float32
 26  prec_threshold      799338 non-null  float32
 27  velmedia_threshold  799338 non-null  float32
 28  racha_threshold     799338 non-null  float32
 29  extreme_tmax        797485 non-null  boolean
 30  extreme_tmin        797298 non-null  boolean
 31  extreme_prec        762512 non-null  boolean
 32  extreme_velmedia    792692 non-null  boolean
 33  extreme_racha       787871 non-null  boolean
dtypes: boolean(5), category(3), datetime64[ns](1), float32(20), int16(3), int8(2)
memory usage: 84.6 MB

In [10]:
df_clm = pd.read_parquet('datasets_clm/main/LABELED_AEMET_ERA5.parquet')
df_clm[cols].describe()

       extreme_tmax extreme_tmin extreme_prec extreme_racha extreme_velmedia
count        339698       339698       339698        339698           339698
unique            2            2            2             2                2
top           False        False        False         False            False
freq         309338       318012       317461        316460           317216

In [11]:
df_clm[['velmedia_threshold', 'racha_threshold', 'tmax_threshold', 'tmin_threshold', 'prec_threshold']].isna().sum().to_list()

[0, 0, 0, 0, 0]

In [12]:
df_clm

,fecha,indicativo,nombre,provincia,tmed,tmax,tmin,velmedia,racha,hrMedia,...,tmax_threshold,tmin_threshold,prec_threshold,velmedia_threshold,racha_threshold,extreme_tmax,extreme_tmin,extreme_prec,extreme_velmedia,extreme_racha
0,2010-01-01,3040Y,BETETA,CUENCA,273.549988,275.049988,272.049988,7.047186,18.649223,97.000000,...,284.829987,265.529999,0.005843,5.775587,17.395061,False,False,True,True,True
1,2010-01-01,3044X,CAÑIZARES,CUENCA,275.183136,276.198975,271.523193,6.074150,16.899223,90.937180,...,288.290009,266.010010,0.015560,4.868420,15.553350,False,False,False,True,True
2,2010-01-01,3094B,TARANCÓN,CUENCA,277.850006,280.350006,275.350006,6.700000,16.900000,81.000000,...,287.489990,270.069977,0.003310,5.240000,15.300000,False,False,False,True,True
3,2010-01-01,3099Y,OCAÑA,TOLEDO,278.250000,280.750000,275.750000,5.000000,16.700001,86.000000,...,286.949982,269.390015,0.005320,4.880000,12.800000,False,False,False,True,True
4,2010-01-01,3103,PANTANO EL VADO,GUADALAJARA,278.649994,281.149994,276.149994,3.882464,17.063843,80.545685,...,288.630005,269.869995,0.007960,2.740000,12.740000,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339693,2023-08-13,9377Y,EL PEDREGAL,GUADALAJARA,298.375305,305.637695,291.536377,2.923433,11.300217,47.013905,...,306.649994,279.913116,0.002960,3.900000,13.260000,False,False,False,False,False
339694,2023-08-14,9377Y,EL PEDREGAL,GUADALAJARA,298.953339,305.494629,291.397461,3.544437,10.932121,36.838139,...,306.509979,281.229980,0.004920,3.900000,13.040000,False,False,False,False,False
339695,2023-08-15,9377Y,EL PEDREGAL,GUADALAJARA,298.429718,305.927490,289.631836,2.117378,9.880010,37.103329,...,307.355438,281.229980,0.002709,3.900000,12.800000,False,False,False,False,False
339696,2023-08-16,9377Y,EL PEDREGAL,GUADALAJARA,298.576172,305.265869,290.948730,2.302533,9.737547,37.403439,...,307.769989,281.229980,0.001492,3.900000,12.904826,False,False,False,False,False
339697,2023-08-17,9377Y,EL PEDREGAL,GUADALAJARA,298.483246,305.991211,289.057617,1.187324,7.699280,34.713051,...,307.769989,281.569977,0.001492,3.900000,12.904826,False,False,False,False,False

In [13]:
df_clm.info()

<class 'pandas.DataFrame'>
RangeIndex: 339698 entries, 0 to 339697
Data columns (total 32 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   fecha               339698 non-null  datetime64[ns]
 1   indicativo          339698 non-null  str
 2   nombre              339698 non-null  str
 3   provincia           339698 non-null  str
 4   tmed                339698 non-null  float32
 5   tmax                339698 non-null  float32
 6   tmin                339698 non-null  float32
 7   velmedia            339698 non-null  float32
 8   racha               339698 non-null  float32
 9   hrMedia             339698 non-null  float32
 10  prec                339698 non-null  float32
 11  anio                339698 non-null  int16
 12  mes                 339698 non-null  int8
 13  dia                 339698 non-null  int8
 14  diaAnio             339698 non-null  int16
 15  altitud             339698 non-null  int16
 16  longitud            339698 non-null  float32
 17  latitud             339698 non-null  float32
 18  mslp_media          339698 non-null  float32
 19  mslp_max            339698 non-null  float32
 20  mslp_min            339698 non-null  float32
 21  source              339698 non-null  str
 22  tmax_threshold      339698 non-null  float32
 23  tmin_threshold      339698 non-null  float32
 24  prec_threshold      339698 non-null  float32
 25  velmedia_threshold  339698 non-null  float32
 26  racha_threshold     339698 non-null  float32
 27  extreme_tmax        339698 non-null  boolean
 28  extreme_tmin        339698 non-null  boolean
 29  extreme_prec        339698 non-null  boolean
 30  extreme_velmedia    339698 non-null  boolean
 31  extreme_racha       339698 non-null  boolean
dtypes: boolean(5), datetime64[ns](1), float32(17), int16(3), int8(2), str(4)
memory usage: 50.9 MB

In [14]:
df_clm.describe()

,fecha,tmed,tmax,tmin,velmedia,racha,hrMedia,prec,anio,mes,...,longitud,latitud,mslp_media,mslp_max,mslp_min,tmax_threshold,tmin_threshold,prec_threshold,velmedia_threshold,racha_threshold
count,339698,339698.000000,339698.000000,339698.000000,339698.000000,339698.000000,339698.000000,339698.000000,339698.000000,339698.000000,...,339698.000000,339698.000000,339698.000000,339698.000000,339698.000000,339698.000000,339698.000000,339698.000000,339698.000000,339698.000000
mean,2017-07-02 00:00:00,287.924957,294.263824,281.479065,2.429437,9.586560,57.369488,0.001059,2017.000730,6.522723,...,-2.981514,39.582020,101752.773438,101979.976562,101518.046875,299.731293,276.622620,0.005398,4.657912,14.977445
min,2010-01-01 00:00:00,257.949982,267.949982,247.949997,0.000000,0.000000,9.000000,0.000000,2010.000000,1.000000,...,-5.114444,38.088333,96829.593750,97111.984375,96361.914062,282.804474,260.029999,0.000000,1.400000,8.540000
25%,2013-10-01 00:00:00,281.549988,286.549988,276.049988,1.400000,7.200000,41.000000,0.000000,2013.000000,4.000000,...,-3.741945,38.954166,101345.478516,101558.896484,101108.951172,291.970001,270.809998,0.001840,3.680000,13.200000
50%,2017-07-02 00:00:00,287.108093,293.359253,281.149994,2.200000,9.200000,57.000000,0.000000,2017.000000,7.000000,...,-2.840556,39.555279,101692.261719,101911.097656,101462.503906,299.784607,275.750000,0.004548,4.540000,14.671245
75%,2021-04-02 00:00:00,294.350006,302.049988,286.949982,3.169266,11.400000,73.168291,0.000200,2021.000000,10.000000,...,-2.199722,40.067223,102146.195312,102374.437500,101927.062500,307.071014,282.239929,0.007760,5.531740,16.420000
max,2024-12-31 00:00:00,309.350006,318.850006,301.949982,14.400000,38.099998,100.000000,0.131400,2024.000000,12.000000,...,-1.063056,41.086388,104553.531250,106215.328125,104418.031250,315.749969,291.850006,0.039680,11.580000,25.860001
std,NaN,7.853357,9.251489,6.957336,1.466677,3.475641,19.828968,0.003810,4.320697,3.448765,...,0.998288,0.766584,667.461792,651.559265,696.557861,8.220506,6.817063,0.004609,1.297336,2.446638