# 1. Imports y config

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
from config import CONFIG

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
np.random.seed(42)

# 2. Carga de datos

In [4]:
from models import load_data

In [5]:
spain_df, spain_feats = load_data(CONFIG["out_features_spain"], CONFIG["reg_path_spain"])

Datos cargados desde data/processed/features_df_spain.parquet: (799338, 132)
    Número de estaciones de datos: 66
Registro de características cargado desde data/processed/feature_reg_spain.csv
    Longitud vista completa: 100
    Longitud vista mínima: 28

In [6]:
clm_df, clm_feats = load_data(CONFIG["out_features_clm"], CONFIG["reg_path_clm"])

Datos cargados desde data/processed/features_df_clm.parquet: (339698, 130)
    Número de estaciones de datos: 62
Registro de características cargado desde data/processed/feature_reg_clm.csv
    Longitud vista completa: 100
    Longitud vista mínima: 28

# 3. Pruebas

In [7]:
from models import feature_view, keep_mask, load_experiment

## 3.1. Vistas

In [8]:
print(f"Primeras 8 columnas de lista completa ({len(feature_view(spain_feats, 'curated'))}):")
print(f"    {feature_view(spain_feats, 'curated')[:8]}")
print(f"Primeras 8 columnas de vista minima ({len(feature_view(spain_feats, 'minimal'))}):")
print(f"    {feature_view(spain_feats, 'minimal')[:8]}")

Primeras 8 columnas de lista completa (100):
    ['altitud', 'anio', 'cos_doy', 'days_since_prec', 'days_since_prec_ex', 'days_since_racha_ex', 'days_since_tmax_ex', 'days_since_tmin_ex']
Primeras 8 columnas de vista minima (28):
    ['altitud', 'anio', 'cos_doy', 'fecha', 'hrMedia', 'indicativo', 'koppen_class', 'koppen_main']

## 3.2. Eliminación de registros que se asoman a splits posteriores

In [9]:
keep = keep_mask(spain_df, 7)
print(f"Se guarda un {keep.mean():.3%} de los registros")
print("Últimos 8 registros eliminados del conjunto de entrenamiento para N=7:")
for _, row in spain_df.loc[~keep].loc[(spain_df["split"] == "train")].tail(8).iterrows():
    print(f"    {row.nombre} - {row.fecha.date()}")

Se guarda un 99.827% de los registros
Últimos 8 registros eliminados del conjunto de entrenamiento para N=7:
    GRAN CANARIA AEROPUERTO - 2018-12-31
    HIERRO AEROPUERTO - 2018-12-25
    HIERRO AEROPUERTO - 2018-12-26
    HIERRO AEROPUERTO - 2018-12-27
    HIERRO AEROPUERTO - 2018-12-28
    HIERRO AEROPUERTO - 2018-12-29
    HIERRO AEROPUERTO - 2018-12-30
    HIERRO AEROPUERTO - 2018-12-31

## 3.3. Creación de experimento

In [10]:
_ex = load_experiment(spain_df, "tmax", 1, "curated", spain_feats)
print(f"Experimento para tmax con N={_ex["N"]}")
print(f"    primeras 5 columnas {_ex["cols"][:5]}")
for split in ["train", "val", "test"]:
    print(f"    {split}:\tX={_ex[split]["X"].shape}\tprevalencia={_ex[split]["y"].mean():.2%}")

Experimento para tmax con N=1
    primeras 5 columnas ['altitud', 'anio', 'cos_doy', 'days_since_prec', 'days_since_prec_ex']
    train:	X=(654916, 100)	prevalencia=5.19%
    val:	X=(72186, 100)	prevalencia=8.12%
    test:	X=(72038, 100)	prevalencia=14.03%

## 3.4. Prueba de baseline de persistencia

In [11]:
from models import conditional_probability_baseline

In [12]:
_base = conditional_probability_baseline(spain_df, "tmax", 1, spain_feats)
print("Baseline de persistencia para tmax con N=1 calculado sobre train")
unique_probs = np.unique(_base["train"])
print(f"   P(target=1 | extremo=1): {unique_probs.max()}")
print(f"   P(target=1 | extremo=0): {unique_probs.min()}")

Baseline de persistencia para tmax con N=1 calculado sobre train
   P(target=1 | extremo=1): 0.3497529702387954
   P(target=1 | extremo=0): 0.03563145824206973

## 3.5. Prueba de métricas con baseline de probabilidad condicional

In [13]:
from models import evaluate

In [14]:
res = evaluate(_ex["train"]["y"], _base["train"])
print("Resultados de evaluación de probabilidad condicional para tmax con N=1:")
for metric, value in res.items():
    if metric != "confusion":
        print(f"{metric:<9}: {value:0.4f}")
    else:
        print(f"{metric:<9}:\n{pd.DataFrame(value)}")

Resultados de evaluación de probabilidad condicional para tmax con N=1:
prevalence: 0.0519
AP       : 0.1561
ROC_AUC  : 0.6570
threshold: 0.0400
F1       : 0.3497
precision: 0.3498
recall   : 0.3496
accuracy : 0.9325
confusion:
        0      1
0  598788  22111
1   22124  11893

## 3.6. Prueba del preprocesado

In [15]:
from models import GroupedTimeWindowStandardScaler, GroupedMinMaxScaler

In [16]:
GroupedTimeWindowStandardScaler(
    "indicativo", "fecha", CONFIG["core_half_window"], CONFIG["core_scale_cols"]
).fit_transform(_ex["train"]["X"])[["tmax", "tmin", "prec", "racha"]].head()

       tmax      tmin      prec     racha
0 -0.768698  0.223038 -0.282523 -0.920079
1 -0.046475 -0.035443 -0.281797 -1.074788
2 -0.409557  0.808258 -0.159574 -0.586298
3  0.109955  0.979524  0.034640 -0.233185
4 -0.263630  0.094453 -0.302371 -0.555037

In [17]:
GroupedMinMaxScaler(
    "indicativo", ["tmax_diff_1"], feature_range=(-1, 1)
).fit_transform(_ex["train"]["X"])[["tmax", "tmax_diff_1"]].head(10)

   tmax  tmax_diff_1
0  12.6          NaN
1  14.7     0.358779
2  13.4     0.099237
3  15.0     0.320611
4  13.6     0.091603
5  14.6     0.274809
6  10.5    -0.114504
7  13.0     0.389313
8  11.9     0.114504
9  12.6     0.251909

In [18]:
from models import make_preprocessor

In [19]:
pre = make_preprocessor(_ex["train"]["X"], _ex["cols"], passthrough=False, core_only=True)
pre

Pipeline(steps=[('impute_encode',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute',
                                                  SimpleImputer(strategy='median'),
                                                  ['altitud', 'anio', 'cos_doy',
                                                   'days_since_prec',
                                                   'days_since_prec_ex',
                                                   'days_since_racha_ex',
                                                   'days_since_tmax_ex',
                                                   'days_since_tmin_ex',
                                                   'extreme_prec_lag_1',
                                                   'extreme_racha_lag_1',
                                                   'extreme_tmax_lag_1',
                                                   'extreme_tmin_lag_1',
                                                   'h...
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['koppen_main',
                                                   'koppen_class'])],
                                   verbose_feature_names_out=False)),
                ('core_scaler',
                 GroupedTimeWindowStandardScaler(cols=['tmax', 'tmin', 'prec',
                                                       'racha', 'tmed',
                                                       'hrMedia', 'mslp_max',
                                                       'mslp_min', 'mslp_media',
                                                       'velmedia'],
                                                 date_col='fecha',
                                                 group_col='indicativo',
                                                 window=2)),
                ('drop_aux', DropCols(cols=['indicativo', 'fecha']))])

In [20]:
pre_train = pre.fit_transform(_ex["train"]["X"]).head()
print(f"{pre_train.isna().sum().sum()} valores perdidos en train")
pre_train.head()

0 valores perdidos en train

,altitud,anio,cos_doy,days_since_prec,days_since_prec_ex,days_since_racha_ex,days_since_tmax_ex,days_since_tmin_ex,extreme_prec_lag_1,extreme_racha_lag_1,extreme_tmax_lag_1,extreme_tmin_lag_1,hrMedia,latitud,longitud,mslp_max,mslp_max_diff_1,mslp_max_diff_3,mslp_max_lag_1,mslp_max_lag_3,mslp_media,mslp_min,mslp_min_diff_1,mslp_min_diff_3,mslp_min_lag_1,mslp_min_lag_3,prec,prec_diff_1,prec_diff_3,prec_dist_to_ex,prec_ewma_14,prec_ewma_3,prec_ewma_7,prec_ex_today,prec_lag_1,prec_lag_3,prec_roll_14_max,prec_roll_14_mean,prec_roll_14_sum,prec_roll_3_max,prec_roll_3_mean,prec_roll_3_sum,prec_roll_7_max,prec_roll_7_mean,prec_roll_7_sum,racha,racha_diff_1,racha_diff_3,racha_dist_to_ex,racha_ewma_14,racha_ewma_3,racha_ewma_7,racha_ex_today,racha_lag_1,racha_lag_3,racha_roll_14_max,racha_roll_14_mean,racha_roll_3_max,racha_roll_3_mean,racha_roll_7_max,racha_roll_7_mean,sin_doy,tmax,tmax_diff_1,tmax_diff_3,tmax_dist_to_ex,tmax_ewma_14,tmax_ewma_3,tmax_ewma_7,tmax_ex_today,tmax_lag_1,tmax_lag_3,tmax_roll_14_max,tmax_roll_14_mean,tmax_roll_3_max,tmax_roll_3_mean,tmax_roll_7_max,tmax_roll_7_mean,tmed,tmin,tmin_diff_1,tmin_diff_3,tmin_dist_to_ex,tmin_ewma_14,tmin_ewma_3,tmin_ewma_7,tmin_ex_today,tmin_lag_1,tmin_lag_3,tmin_roll_14_max,tmin_roll_14_mean,tmin_roll_3_max,tmin_roll_3_mean,tmin_roll_7_max,tmin_roll_7_mean,velmedia,koppen_main_B,koppen_main_C,koppen_class_BSh,koppen_class_BSk,koppen_class_BWh,koppen_class_Cfa,koppen_class_Cfb,koppen_class_Csa,koppen_class_Csb
0,71.0,1990.0,0.999852,3.0,18.0,17.0,22.0,23.0,0.0,0.0,0.0,0.0,1.495262,41.145,1.163611,-0.176379,-0.033081,-0.041809,1019.331238,1019.329926,-0.040223,0.077678,-0.024353,-0.057312,1015.371643,1015.369995,-0.276154,0.0,0.0,-7.01,0.000000,0.000000,0.000000,0.0,0.0,0.0,3.7,0.392857,5.5,0.0,0.000000,0.0,0.8,0.128571,0.9,-0.932126,0.0,0.0,-16.725000,5.000000,5.000000,5.000000,0.0,9.7,9.7,15.8,10.042857,11.9,9.833333,13.9,9.985714,0.017202,-0.768698,0.100000,0.000000,-7.580000,12.600000,12.600000,12.600000,0.0,21.6,21.6,25.799999,21.628572,23.1,21.633333,24.5,21.642857,-0.214955,0.223038,-0.1,0.0,-7.40,5.400000,5.400000,5.400000,0.0,12.3,12.3,15.6,12.085714,13.6,12.200000,14.8,12.142857,-1.112509,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,71.0,1990.0,0.999408,3.0,18.0,17.0,22.0,23.0,0.0,0.0,0.0,0.0,1.458801,41.145,1.163611,-0.290058,-0.920227,-0.041809,1021.398560,1019.329926,-0.161453,-0.048223,-1.525269,-0.057312,1017.868469,1015.369995,-0.273308,0.0,0.0,-7.02,0.000000,0.000000,0.000000,0.0,0.0,0.0,3.7,0.392857,5.5,0.0,0.000000,0.0,0.8,0.128571,0.9,-1.088441,-0.8,0.0,-18.014999,4.571428,4.466667,4.542857,0.0,5.0,9.7,15.8,10.042857,11.9,9.833333,13.9,9.985714,0.034398,-0.061022,2.099999,0.000000,-5.485002,13.725000,14.000000,13.800000,0.0,12.6,21.6,25.799999,21.628572,23.1,21.633333,24.5,21.642857,-0.075500,-0.047559,-1.2,0.0,-6.20,4.757143,4.600000,4.714286,0.0,5.4,12.3,15.6,12.085714,13.6,12.200000,14.8,12.142857,-1.126200,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,71.0,1990.0,0.998669,0.0,18.0,17.0,22.0,23.0,0.0,0.0,0.0,0.0,1.517506,41.145,1.163611,-0.809166,-4.168152,-0.041809,1020.478333,1019.329926,-0.682369,-0.558287,-4.874023,-0.057312,1016.343201,1015.369995,-0.145147,0.5,0.0,-5.75,0.191002,0.285714,0.216216,0.0,0.0,0.0,3.7,0.392857,5.5,0.5,0.166667,0.5,0.8,0.128571,0.9,-0.593038,2.7,0.0,-15.300001,5.460951,5.857143,5.562162,0.0,4.2,9.7,15.8,10.042857,6.9,5.366667,13.9,9.985714,0.051584,-0.428876,-1.300000,0.000000,-6.790001,13.600849,13.657143,13.627027,0.0,14.7,21.6,25.799999,21.628572,14.7,13.566667,24.5,21.642857,0.285019,0.766837,3.3,0.0,-9.48,5.804924,6.257143,5.918919,0.0,4.2,12.3,15.6,12.085714,7.5,5.700000,14.8,12.142857,0.127882,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,71.0,1990.0,0.997634,0.0,18.0,17.0,22.0,23.0,0.0,0.0,0.0,0.0,0.443588,41.145,1.163611,0.384255,9.450073,4.361694,1016.310181,1021.398560,-0.000520,-0.327546,1.886414,-4.512878,1011.469177,1017.868469,0.054627,0.8,1.3,-6.05,0.530276,0.826667,0.612571,0.0,0.5,0.0,3.7,0.392857,5.5,1.3,0.600000,1.8,0.8,0.128571,0.9,-0.233793,2.0,3.9,-12.785002,6.513053,7.480000,6.782857,0.0,6.9,5.0,15.8,10.042857,8.9,6.666667,13.9,9.985714,0.068755,0.077895,1.600000,2.400000,-5.369999,14.028889,14.373333,14.129143,0.0,13.4,12.6,25.799999,21.628572,15.0,14.366666,24.5,21.642857,0.644056,0.931756,0.5,2.6,-9.80,6.476459,7.186667,6.680000,0.0,7.5,5.4,15.6,12.085714,8.0,6.566667,14.8,12.142857,-0.102667,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,71.0,1990.0,0.996303,1.0,18.0,17.0,22.0,23.0,0.0,0.0,0.0,0.0,1.471962,41.145,1.163611,0.731603,3.009033,8.290955,1025.760254,1020.478333,0.812976,0.862607,12.488647,9.501038,1013.355591,1016.343201,-0.289748,-1.3,0.0,-10.22,0.391927,0.400000,0.411780,0.0,1.3,0.0,3.7,0.392857,5.5,1.3,0.600000,1.8,0.8,0.128571,0.9,-0.562681,-2.0,2.7,-14.200001,6.614007,7.180645,6.821255,0.0,8.9,4.2,15.8,10.042857,8.9,7.566667,13.9,9.985714,0.085906,-0.286060,-1.400000,-1.099999,-6.980000,13.916992,13.974194,13.955698,0.0,15.0,14.7,25.799999,21.628572,15.0,14.000000,24.5,21.642857,-0.117373,0.062099,-4.0,-0.2,-5.80,5.830355,5.541935,5.801536,0.0,8.0,4.2,15.6,12.085714,8.0,6.500000,14.8,12.142857,-0.607515,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [21]:
pre_val = pre.transform(_ex["val"]["X"]).head()
print(f"{pre_val.isna().sum().sum()} valores perdidos en val")
pre_val.head()

0 valores perdidos en val

,altitud,anio,cos_doy,days_since_prec,days_since_prec_ex,days_since_racha_ex,days_since_tmax_ex,days_since_tmin_ex,extreme_prec_lag_1,extreme_racha_lag_1,extreme_tmax_lag_1,extreme_tmin_lag_1,hrMedia,latitud,longitud,mslp_max,mslp_max_diff_1,mslp_max_diff_3,mslp_max_lag_1,mslp_max_lag_3,mslp_media,mslp_min,mslp_min_diff_1,mslp_min_diff_3,mslp_min_lag_1,mslp_min_lag_3,prec,prec_diff_1,prec_diff_3,prec_dist_to_ex,prec_ewma_14,prec_ewma_3,prec_ewma_7,prec_ex_today,prec_lag_1,prec_lag_3,prec_roll_14_max,prec_roll_14_mean,prec_roll_14_sum,prec_roll_3_max,prec_roll_3_mean,prec_roll_3_sum,prec_roll_7_max,prec_roll_7_mean,prec_roll_7_sum,racha,racha_diff_1,racha_diff_3,racha_dist_to_ex,racha_ewma_14,racha_ewma_3,racha_ewma_7,racha_ex_today,racha_lag_1,racha_lag_3,racha_roll_14_max,racha_roll_14_mean,racha_roll_3_max,racha_roll_3_mean,racha_roll_7_max,racha_roll_7_mean,sin_doy,tmax,tmax_diff_1,tmax_diff_3,tmax_dist_to_ex,tmax_ewma_14,tmax_ewma_3,tmax_ewma_7,tmax_ex_today,tmax_lag_1,tmax_lag_3,tmax_roll_14_max,tmax_roll_14_mean,tmax_roll_3_max,tmax_roll_3_mean,tmax_roll_7_max,tmax_roll_7_mean,tmed,tmin,tmin_diff_1,tmin_diff_3,tmin_dist_to_ex,tmin_ewma_14,tmin_ewma_3,tmin_ewma_7,tmin_ex_today,tmin_lag_1,tmin_lag_3,tmin_roll_14_max,tmin_roll_14_mean,tmin_roll_3_max,tmin_roll_3_mean,tmin_roll_7_max,tmin_roll_7_mean,velmedia,koppen_main_B,koppen_main_C,koppen_class_BSh,koppen_class_BSk,koppen_class_BWh,koppen_class_Cfa,koppen_class_Cfb,koppen_class_Csa,koppen_class_Csb
0,71.0,2019.0,0.999852,8.0,42.0,62.0,28.0,63.0,0.0,0.0,0.0,0.0,-0.152387,41.145,1.163611,0.881797,0.407715,0.148438,1029.761841,1030.021118,0.991417,1.059252,0.306763,-0.154053,1027.038696,1027.499512,-0.276154,0.0,0.0,-7.01,0.061479,4.682292e-06,0.005420,0.0,0.0,0.0,3.7,0.392857,5.5,0.0,0.0,0.0,0.0,0.0,0.0,-0.446992,3.1,0.6,-13.925000,7.091407,6.423162,6.287932,0.0,4.7,7.2,17.5,7.421429,7.8,5.566667,7.8,5.914286,0.017202,1.037162,-0.799999,4.000000,-2.180000,16.475911,17.477973,16.671462,0.0,18.799999,14.000000,19.4,16.714286,18.799999,17.633333,18.799999,15.585714,-0.087575,-0.856934,0.6,-0.3,-2.80,2.785871,0.727884,1.621254,0.0,0.2,1.1,6.9,3.342857,0.8,0.333333,5.6,1.957143,-0.638286,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,71.0,2019.0,0.999408,9.0,43.0,63.0,29.0,64.0,0.0,0.0,0.0,0.0,0.418467,41.145,1.163611,0.569148,-2.754028,-2.695435,1030.169556,1030.110962,0.719572,0.826537,-2.653320,-1.989502,1027.345459,1026.681641,-0.273308,0.0,0.0,-7.02,0.052889,2.338855e-06,0.004037,0.0,0.0,0.0,3.7,0.392857,5.5,0.0,0.0,0.0,0.0,0.0,0.0,-0.814068,-2.0,1.6,-16.415001,6.919220,6.111581,6.165949,0.0,7.8,4.2,10.3,6.585714,7.8,6.100000,7.8,6.028571,0.034398,0.003589,-3.100000,-1.200001,-5.285002,16.265790,16.188986,16.228597,0.0,18.000000,16.100000,19.4,16.607143,18.799999,17.233333,18.799999,15.500000,-0.741750,-1.080452,-1.2,-0.4,-1.60,2.361088,0.163942,1.115941,0.0,0.8,0.0,6.1,2.821429,0.8,0.200000,3.6,1.100000,-0.638262,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,71.0,2019.0,0.998669,10.0,44.0,64.0,30.0,0.0,0.0,0.0,0.0,0.0,0.201880,41.145,1.163611,0.972090,3.289185,0.942871,1027.415527,1029.761841,1.049967,1.086816,2.683838,0.337280,1024.692139,1027.038696,-0.290095,0.0,0.0,-6.25,0.045546,1.168856e-06,0.003013,0.0,0.0,0.0,3.7,0.392857,5.5,0.0,0.0,0.0,0.0,0.0,0.0,-0.628194,0.9,2.0,-15.500001,6.889990,6.405790,6.299462,0.0,5.8,4.7,10.3,6.328571,7.8,6.766667,7.8,6.028571,0.051584,-0.428876,-1.500000,-5.400000,-6.790001,15.883684,14.794493,15.521447,0.0,14.900000,18.799999,19.4,16.392857,18.000000,15.433333,18.799999,15.542857,-1.269824,-1.568625,-2.1,-2.7,0.52,1.712943,-1.168029,0.211955,1.0,-0.4,0.2,6.1,2.328571,0.8,-0.700000,2.4,0.228571,-0.393785,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,71.0,2019.0,0.997634,11.0,45.0,65.0,31.0,0.0,0.0,0.0,0.0,1.0,-0.589669,41.145,1.163611,1.204464,2.215576,2.750732,1030.704712,1030.169556,1.144253,1.066293,0.299072,0.329590,1027.375977,1027.345459,-0.286338,0.0,0.0,-7.35,0.039258,5.842850e-07,0.002251,0.0,0.0,0.0,3.7,0.392857,5.5,0.0,0.0,0.0,0.0,0.0,0.0,-0.948827,-1.7,-2.8,-16.685001,6.637992,5.702895,5.974596,0.0,6.7,7.8,8.3,5.950000,6.7,5.833333,7.8,5.914286,0.068755,-0.289416,0.400001,-4.200000,-6.569999,15.605860,14.297247,15.091086,0.0,13.400000,18.000000,19.4,16.142857,14.900000,14.033333,18.799999,15.571428,-1.196258,-1.589300,0.0,-3.3,0.70,1.151217,-1.834015,-0.466033,1.0,-2.5,0.8,6.1,1.985714,-0.4,-1.800000,1.1,-0.471429,-0.540513,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,71.0,2019.0,0.996303,12.0,46.0,66.0,32.0,0.0,0.0,0.0,0.0,1.0,-0.507616,41.145,1.163611,1.076883,-1.049561,4.455200,1032.920288,1027.415527,0.975704,0.869594,-1.755493,1.227417,1027.675049,1024.692139,-0.289748,0.0,0.0,-10.22,0.033863,2.921068e-07,0.001684,0.0,0.0,0.0,3.7,0.392857,5.5,0.0,0.0,0.0,0.0,0.0,0.0,0.388098,6.7,5.9,-9.400001,7.312926,8.701447,7.405947,0.0,5.0,5.8,11.7,6.192857,11.7,7.800000,11.7,6.557143,0.085906,0.351183,2.000000,0.900001,-4.780000,15.631745,15.048623,15.268314,0.0,13.800000,14.900000,19.4,15.885714,15.800000,14.333333,18.799999,15.828571,-0.750053,-1.513673,0.2,-1.9,0.50,0.691055,-2.067007,-0.924525,1.0,-2.5,-0.4,6.1,1.442857,-2.3,-2.433333,0.8,-0.957143,-0.607515,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

## 3.7. Prueba de experimento

In [22]:
from models import run_experiment

In [23]:
_, _ = run_experiment(spain_df, "tmax", 1, "Baseline", "curated", spain_feats, "spain")

[tmax, N=1, Baseline]
    Métricas en train
        AP=0.156 | ROC_AUC=0.657
        prev=0.052 | P=0.350 | R=0.350 | F1=0.350 | acc=0.932
    Métricas en val
        AP=0.231 | ROC_AUC=0.689
        prev=0.081 | P=0.430 | R=0.428 | F1=0.429 | acc=0.908
    Métricas en test
        AP=0.344 | ROC_AUC=0.725
        prev=0.140 | P=0.526 | R=0.528 | F1=0.527 | acc=0.867

# 4. Entrenamiento

In [24]:
from models import run_all_experiments

## 4.1. España

### 4.1.1. Vista completa

In [25]:
res_spain_full = run_all_experiments(spain_df, "curated", spain_feats, "spain", verbose=True)

Ejecutando 60 experimentos (4 vars x 3 N x 5 modelos)
Número de iteraciones por modelo: {'NaiveBayes': 10, 'LogReg': 10, 'DecisionTree': 10, 'LGBM': 10} | jobs paralelos: 1

[ 1/60] tmax N=1 Baseline
[tmax, N=1, Baseline]
    Métricas en train
        AP=0.156 | ROC_AUC=0.657
        prev=0.052 | P=0.350 | R=0.350 | F1=0.350 | acc=0.932
    Métricas en val
        AP=0.231 | ROC_AUC=0.689
        prev=0.081 | P=0.430 | R=0.428 | F1=0.429 | acc=0.908
    Métricas en test
        AP=0.344 | ROC_AUC=0.725
        prev=0.140 | P=0.526 | R=0.528 | F1=0.527 | acc=0.867
    Hecho en 1s | transcurrido 0.0 min | tiempo restante estimado ~1.3 min (59 modelos restantes)

[ 2/60] tmax N=1 NaiveBayes
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__var_smoothing=9.91564456663839e-07;, score=0.295 total time=   1.0s
[CV 1/1] END classifier__var_smoothing=0.04033800832600378;, score=0.118 total time=   0.6s
[CV 1/1] END classifier__var_smoothing=0.0007177141927992007;, score=0.142 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=6.155564318973005e-05;, score=0.202 total time=   0.6s
[CV 1/1] END classifier__var_smoothing=1.7707168643537813e-08;, score=0.303 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=1.7699302940633323e-08;, score=0.303 total time=   0.6s
[CV 1/1] END classifier__var_smoothing=2.9152036385288267e-09;, score=0.303 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=0.008499808989182987;, score=0.120 total time=   0.7s
[CV 1/1] END classifier__var_smoothing=6.440507553993706e-05;, score=0.201 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=0.0004619347374377367;, score=0.150 total time=   0.5s
    Búsqueda de 10 sobre 654916 filas en 6.1204 segundos | mejor AP en val: 0.3030
[tmax, N=1, NaiveBayes]
    Métricas en train
        AP=0.242 | ROC_AUC=0.801
        prev=0.052 | P=0.110 | R=0.787 | F1=0.194 | acc=0.660
    Métricas en val
        AP=0.303 | ROC_AUC=0.786
        prev=0.081 | P=0.147 | R=0.809 | F1=0.249 | acc=0.603
    Métricas en test
        AP=0.437 | ROC_AUC=0.806
        prev=0.140 | P=0.230 | R=0.864 | F1=0.363 | acc=0.575
    Hecho en 18s | transcurrido 0.3 min | tiempo restante estimado ~9.5 min (58 modelos restantes)

[ 3/60] tmax N=1 LogReg
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__C=0.005611516415334507;, score=0.379 total time=  12.8s
[CV 1/1] END .classifier__C=0.07969454818643935;, score=0.379 total time=  17.5s
[CV 1/1] END classifier__C=0.029106359131330698;, score=0.379 total time=  13.0s
[CV 1/1] END classifier__C=0.015751320499779727;, score=0.379 total time=  13.9s
[CV 1/1] END classifier__C=0.0020513382630874496;, score=0.379 total time=  10.0s
[CV 1/1] END classifier__C=0.002051110418843397;, score=0.379 total time=  10.3s
[CV 1/1] END classifier__C=0.0013066739238053278;, score=0.379 total time=   9.7s
[CV 1/1] END .classifier__C=0.05399484409787434;, score=0.379 total time=  16.0s
[CV 1/1] END classifier__C=0.015930522616241012;, score=0.379 total time=  13.6s
[CV 1/1] END classifier__C=0.026070247583707677;, score=0.379 total time=  11.5s
    Búsqueda de 10 sobre 654916 filas en 128.4399 segundos | mejor AP en val: 0.3795
[tmax, N=1, LogReg]
    Métricas en train
        AP=0.302 | ROC_AUC=0.876
        prev=0.052 | P=0.325 | R=0.465 | F1=0.383 | acc=0.922
    Métricas en val
        AP=0.379 | ROC_AUC=0.868
        prev=0.081 | P=0.375 | R=0.555 | F1=0.448 | acc=0.889
    Métricas en test
        AP=0.512 | ROC_AUC=0.868
        prev=0.140 | P=0.454 | R=0.674 | F1=0.543 | acc=0.841
    Hecho en 166s | transcurrido 3.1 min | tiempo restante estimado ~58.7 min (57 modelos restantes)

[ 4/60] tmax N=1 DecisionTree
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.379 total time=  44.1s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.401 total time=  35.3s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.342 total time=  17.8s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=sqrt, classifier__min_samples_leaf=100;, score=0.377 total time=   3.9s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=sqrt, classifier__min_samples_leaf=200;, score=0.380 total time=   4.5s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.386 total time=  40.2s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.358 total time=  19.7s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.342 total time=  16.2s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.396 total time=  43.3s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.392 total time=  31.8s
    Búsqueda de 10 sobre 654916 filas en 256.9211 segundos | mejor AP en val: 0.4011
[tmax, N=1, DecisionTree]
    Métricas en train
        AP=0.370 | ROC_AUC=0.895
        prev=0.052 | P=0.357 | R=0.490 | F1=0.413 | acc=0.928
    Métricas en val
        AP=0.401 | ROC_AUC=0.859
        prev=0.081 | P=0.400 | R=0.499 | F1=0.444 | acc=0.898
    Métricas en test
        AP=0.539 | ROC_AUC=0.860
        prev=0.140 | P=0.463 | R=0.618 | F1=0.529 | acc=0.846
    Hecho en 343s | transcurrido 8.8 min | tiempo restante estimado ~123.2 min (56 modelos restantes)

[ 5/60] tmax N=1 LGBM
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.446 total time= 1.3min
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.446 total time= 1.3min
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.449 total time= 1.5min
[CV 1/1] END classifier__bagging_fraction=0.5, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=1.0, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.448 total time= 1.6min
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.446 total time= 1.6min
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.424 total time= 1.0min
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=64;, score=0.405 total time= 1.0min
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.446 total time= 1.7min
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.75, classifier__lambda_l1=0.5, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.422 total time= 1.3min
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.75, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.444 total time= 1.8min
    Búsqueda de 10 sobre 654916 filas en 850.3372 segundos | mejor AP en val: 0.4493
[tmax, N=1, LGBM]
    Métricas en train
        AP=0.413 | ROC_AUC=0.920
        prev=0.052 | P=0.386 | R=0.499 | F1=0.435 | acc=0.933
    Métricas en val
        AP=0.449 | ROC_AUC=0.887
        prev=0.081 | P=0.439 | R=0.522 | F1=0.477 | acc=0.907
    Métricas en test
        AP=0.586 | ROC_AUC=0.883
        prev=0.140 | P=0.509 | R=0.626 | F1=0.562 | acc=0.863
    Hecho en 1080s | transcurrido 26.8 min | tiempo restante estimado ~294.8 min (55 modelos restantes)

[ 6/60] tmax N=3 Baseline
[tmax, N=3, Baseline]
    Métricas en train
        AP=0.184 | ROC_AUC=0.584
        prev=0.117 | P=0.451 | R=0.201 | F1=0.278 | acc=0.878
    Métricas en val
        AP=0.256 | ROC_AUC=0.601
        prev=0.168 | P=0.523 | R=0.248 | F1=0.337 | acc=0.836
    Métricas en test
        AP=0.390 | ROC_AUC=0.635
        prev=0.264 | P=0.635 | R=0.340 | F1=0.443 | acc=0.775
    Hecho en 1s | transcurrido 26.8 min | tiempo restante estimado ~241.4 min (54 modelos restantes)

[ 7/60] tmax N=3 NaiveBayes
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__var_smoothing=9.91564456663839e-07;, score=0.347 total time=   0.7s
[CV 1/1] END classifier__var_smoothing=0.04033800832600378;, score=0.205 total time=   0.6s
[CV 1/1] END classifier__var_smoothing=0.0007177141927992007;, score=0.228 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=6.155564318973005e-05;, score=0.271 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=1.7707168643537813e-08;, score=0.353 total time=   0.6s
[CV 1/1] END classifier__var_smoothing=1.7699302940633323e-08;, score=0.353 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=2.9152036385288267e-09;, score=0.353 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=0.008499808989182987;, score=0.210 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=6.440507553993706e-05;, score=0.270 total time=   0.6s
[CV 1/1] END classifier__var_smoothing=0.0004619347374377367;, score=0.234 total time=   0.6s
    Búsqueda de 10 sobre 654784 filas en 5.8163 segundos | mejor AP en val: 0.3527
[tmax, N=3, NaiveBayes]
    Métricas en train
        AP=0.295 | ROC_AUC=0.721
        prev=0.117 | P=0.205 | R=0.660 | F1=0.313 | acc=0.663
    Métricas en val
        AP=0.353 | ROC_AUC=0.706
        prev=0.168 | P=0.257 | R=0.696 | F1=0.375 | acc=0.611
    Métricas en test
        AP=0.516 | ROC_AUC=0.733
        prev=0.264 | P=0.375 | R=0.777 | F1=0.506 | acc=0.599
    Hecho en 16s | transcurrido 27.1 min | tiempo restante estimado ~205.0 min (53 modelos restantes)

[ 8/60] tmax N=3 LogReg
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__C=0.005611516415334507;, score=0.415 total time=   9.3s
[CV 1/1] END .classifier__C=0.07969454818643935;, score=0.414 total time=  18.1s
[CV 1/1] END classifier__C=0.029106359131330698;, score=0.414 total time=  13.9s
[CV 1/1] END classifier__C=0.015751320499779727;, score=0.415 total time=  11.1s
[CV 1/1] END classifier__C=0.0020513382630874496;, score=0.415 total time=   7.2s
[CV 1/1] END classifier__C=0.002051110418843397;, score=0.415 total time=   7.4s
[CV 1/1] END classifier__C=0.0013066739238053278;, score=0.415 total time=   5.5s
[CV 1/1] END .classifier__C=0.05399484409787434;, score=0.414 total time=  18.3s
[CV 1/1] END classifier__C=0.015930522616241012;, score=0.415 total time=  11.0s
[CV 1/1] END classifier__C=0.026070247583707677;, score=0.414 total time=  11.8s
    Búsqueda de 10 sobre 654784 filas en 113.7106 segundos | mejor AP en val: 0.4153
[tmax, N=3, LogReg]
    Métricas en train
        AP=0.348 | ROC_AUC=0.788
        prev=0.117 | P=0.344 | R=0.483 | F1=0.402 | acc=0.832
    Métricas en val
        AP=0.415 | ROC_AUC=0.771
        prev=0.168 | P=0.372 | R=0.592 | F1=0.457 | acc=0.763
    Métricas en test
        AP=0.574 | ROC_AUC=0.790
        prev=0.264 | P=0.468 | R=0.728 | F1=0.570 | acc=0.710
    Hecho en 141s | transcurrido 29.4 min | tiempo restante estimado ~191.3 min (52 modelos restantes)

[ 9/60] tmax N=3 DecisionTree
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.392 total time=  42.0s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.412 total time=  36.3s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.386 total time=  16.1s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=sqrt, classifier__min_samples_leaf=100;, score=0.409 total time=   3.9s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=sqrt, classifier__min_samples_leaf=200;, score=0.412 total time=   4.6s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.403 total time=  40.0s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.394 total time=  18.2s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.386 total time=  16.2s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.407 total time=  44.8s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.407 total time=  31.3s
    Búsqueda de 10 sobre 654784 filas en 253.6148 segundos | mejor AP en val: 0.4122
[tmax, N=3, DecisionTree]
    Métricas en train
        AP=0.391 | ROC_AUC=0.811
        prev=0.117 | P=0.345 | R=0.536 | F1=0.420 | acc=0.827
    Métricas en val
        AP=0.412 | ROC_AUC=0.751
        prev=0.168 | P=0.377 | R=0.527 | F1=0.440 | acc=0.774
    Métricas en test
        AP=0.564 | ROC_AUC=0.769
        prev=0.264 | P=0.496 | R=0.621 | F1=0.552 | acc=0.734
    Hecho en 271s | transcurrido 34.0 min | tiempo restante estimado ~192.4 min (51 modelos restantes)

[10/60] tmax N=3 LGBM
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.453 total time= 1.3min
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.454 total time= 1.3min
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.454 total time= 1.5min
[CV 1/1] END classifier__bagging_fraction=0.5, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=1.0, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.456 total time= 1.5min
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.452 total time= 1.6min
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.430 total time= 1.0min
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=64;, score=0.423 total time= 1.1min
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.452 total time= 1.8min
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.75, classifier__lambda_l1=0.5, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.417 total time= 1.3min
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.75, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.452 total time= 1.8min
    Búsqueda de 10 sobre 654784 filas en 851.2982 segundos | mejor AP en val: 0.4558
[tmax, N=3, LGBM]
    Métricas en train
        AP=0.441 | ROC_AUC=0.847
        prev=0.117 | P=0.345 | R=0.657 | F1=0.452 | acc=0.815
    Métricas en val
        AP=0.456 | ROC_AUC=0.789
        prev=0.168 | P=0.380 | R=0.615 | F1=0.470 | acc=0.767
    Métricas en test
        AP=0.612 | ROC_AUC=0.803
        prev=0.264 | P=0.464 | R=0.757 | F1=0.576 | acc=0.706
    Hecho en 1081s | transcurrido 52.0 min | tiempo restante estimado ~259.9 min (50 modelos restantes)

[11/60] tmax N=7 Baseline
[tmax, N=7, Baseline]
    Métricas en train
        AP=0.264 | ROC_AUC=0.550
        prev=0.221 | P=0.221 | R=1.000 | F1=0.363 | acc=0.221
    Métricas en val
        AP=0.358 | ROC_AUC=0.560
        prev=0.306 | P=0.306 | R=1.000 | F1=0.469 | acc=0.306
    Métricas en test
        AP=0.517 | ROC_AUC=0.590
        prev=0.440 | P=0.440 | R=1.000 | F1=0.611 | acc=0.440
    Hecho en 1s | transcurrido 52.0 min | tiempo restante estimado ~231.6 min (49 modelos restantes)

[12/60] tmax N=7 NaiveBayes
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__var_smoothing=9.91564456663839e-07;, score=0.446 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=0.04033800832600378;, score=0.342 total time=   0.6s
[CV 1/1] END classifier__var_smoothing=0.0007177141927992007;, score=0.364 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=6.155564318973005e-05;, score=0.392 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=1.7707168643537813e-08;, score=0.454 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=1.7699302940633323e-08;, score=0.454 total time=   0.7s
[CV 1/1] END classifier__var_smoothing=2.9152036385288267e-09;, score=0.454 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=0.008499808989182987;, score=0.348 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=6.440507553993706e-05;, score=0.391 total time=   0.5s
[CV 1/1] END classifier__var_smoothing=0.0004619347374377367;, score=0.368 total time=   0.5s
    Búsqueda de 10 sobre 654520 filas en 5.3881 segundos | mejor AP en val: 0.4543
[tmax, N=7, NaiveBayes]
    Métricas en train
        AP=0.373 | ROC_AUC=0.656
        prev=0.221 | P=0.278 | R=0.752 | F1=0.406 | acc=0.513
    Métricas en val
        AP=0.454 | ROC_AUC=0.643
        prev=0.306 | P=0.356 | R=0.787 | F1=0.490 | acc=0.499
    Métricas en test
        AP=0.630 | ROC_AUC=0.680
        prev=0.440 | P=0.502 | R=0.843 | F1=0.629 | acc=0.563
    Hecho en 17s | transcurrido 52.3 min | tiempo restante estimado ~209.1 min (48 modelos restantes)

[13/60] tmax N=7 LogReg
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__C=0.005611516415334507;, score=0.490 total time=   7.5s
[CV 1/1] END .classifier__C=0.07969454818643935;, score=0.488 total time=  17.6s

### 4.1.2. Vista mínima

In [26]:
res_spain_min = run_all_experiments(spain_df, "minimal", spain_feats, "spain", verbose=True)

Ejecutando 60 experimentos (4 vars x 3 N x 5 modelos)
Número de iteraciones por modelo: {'NaiveBayes': 10, 'LogReg': 10, 'DecisionTree': 10, 'LGBM': 10} | jobs paralelos: 1

[ 1/60] tmax N=1 Baseline
[tmax, N=1, Baseline]
    Métricas en train
        AP=0.156 | ROC_AUC=0.657
        prev=0.052 | P=0.350 | R=0.350 | F1=0.350 | acc=0.932
    Métricas en val
        AP=0.231 | ROC_AUC=0.689
        prev=0.081 | P=0.430 | R=0.428 | F1=0.429 | acc=0.908
    Métricas en test
        AP=0.344 | ROC_AUC=0.725
        prev=0.140 | P=0.526 | R=0.528 | F1=0.527 | acc=0.867
    Hecho en 1s | transcurrido 0.0 min | tiempo restante estimado ~1.4 min (59 modelos restantes)

[ 2/60] tmax N=1 NaiveBayes
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__var_smoothing=9.91564456663839e-07;, score=0.384 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.04033800832600378;, score=0.260 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.0007177141927992007;, score=0.367 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=6.155564318973005e-05;, score=0.377 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=1.7707168643537813e-08;, score=0.379 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=1.7699302940633323e-08;, score=0.379 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=2.9152036385288267e-09;, score=0.379 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.008499808989182987;, score=0.315 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=6.440507553993706e-05;, score=0.377 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.0004619347374377367;, score=0.371 total time=   0.3s
    Búsqueda de 10 sobre 654916 filas en 2.0341 segundos | mejor AP en val: 0.3838
[tmax, N=1, NaiveBayes]
    Métricas en train
        AP=0.306 | ROC_AUC=0.860
        prev=0.052 | P=0.320 | R=0.453 | F1=0.375 | acc=0.921
    Métricas en val
        AP=0.384 | ROC_AUC=0.853
        prev=0.081 | P=0.382 | R=0.522 | F1=0.441 | acc=0.893
    Métricas en test
        AP=0.519 | ROC_AUC=0.859
        prev=0.140 | P=0.477 | R=0.602 | F1=0.533 | acc=0.852
    Hecho en 6s | transcurrido 0.1 min | tiempo restante estimado ~3.7 min (58 modelos restantes)

[ 3/60] tmax N=1 LogReg
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__C=0.005611516415334507;, score=0.379 total time=   1.6s
[CV 1/1] END .classifier__C=0.07969454818643935;, score=0.379 total time=   1.8s
[CV 1/1] END classifier__C=0.029106359131330698;, score=0.379 total time=   2.0s
[CV 1/1] END classifier__C=0.015751320499779727;, score=0.379 total time=   1.8s
[CV 1/1] END classifier__C=0.0020513382630874496;, score=0.378 total time=   2.2s
[CV 1/1] END classifier__C=0.002051110418843397;, score=0.378 total time=   2.3s
[CV 1/1] END classifier__C=0.0013066739238053278;, score=0.377 total time=   1.5s
[CV 1/1] END .classifier__C=0.05399484409787434;, score=0.379 total time=   1.5s
[CV 1/1] END classifier__C=0.015930522616241012;, score=0.379 total time=   1.8s
[CV 1/1] END classifier__C=0.026070247583707677;, score=0.379 total time=   1.7s
    Búsqueda de 10 sobre 654916 filas en 18.2658 segundos | mejor AP en val: 0.3791
[tmax, N=1, LogReg]
    Métricas en train
        AP=0.302 | ROC_AUC=0.872
        prev=0.052 | P=0.311 | R=0.497 | F1=0.382 | acc=0.917
    Métricas en val
        AP=0.379 | ROC_AUC=0.866
        prev=0.081 | P=0.358 | R=0.581 | F1=0.443 | acc=0.881
    Métricas en test
        AP=0.513 | ROC_AUC=0.866
        prev=0.140 | P=0.436 | R=0.693 | F1=0.535 | acc=0.831
    Hecho en 26s | transcurrido 0.6 min | tiempo restante estimado ~10.6 min (57 modelos restantes)

[ 4/60] tmax N=1 DecisionTree
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.376 total time=  11.4s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.393 total time=  10.0s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.339 total time=   4.7s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=sqrt, classifier__min_samples_leaf=100;, score=0.368 total time=   1.9s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=sqrt, classifier__min_samples_leaf=200;, score=0.380 total time=   1.9s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.387 total time=  11.1s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.360 total time=   5.4s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.339 total time=   4.7s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.391 total time=  11.7s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.386 total time=   8.7s
    Búsqueda de 10 sobre 654916 filas en 71.4957 segundos | mejor AP en val: 0.3930
[tmax, N=1, DecisionTree]
    Métricas en train
        AP=0.368 | ROC_AUC=0.891
        prev=0.052 | P=0.310 | R=0.559 | F1=0.399 | acc=0.912
    Métricas en val
        AP=0.393 | ROC_AUC=0.862
        prev=0.081 | P=0.362 | R=0.566 | F1=0.441 | acc=0.884
    Métricas en test
        AP=0.533 | ROC_AUC=0.861
        prev=0.140 | P=0.452 | R=0.649 | F1=0.533 | acc=0.840
    Hecho en 96s | transcurrido 2.2 min | tiempo restante estimado ~30.2 min (56 modelos restantes)

[ 5/60] tmax N=1 LGBM
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.423 total time=  37.0s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.423 total time=  33.9s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.425 total time=  39.3s
[CV 1/1] END classifier__bagging_fraction=0.5, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=1.0, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.426 total time=  46.6s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.422 total time=  36.7s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.400 total time=  26.9s
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=64;, score=0.371 total time=  23.0s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.421 total time=  39.0s
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.75, classifier__lambda_l1=0.5, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.368 total time=  24.2s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.75, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.423 total time=  36.6s
    Búsqueda de 10 sobre 654916 filas en 343.3491 segundos | mejor AP en val: 0.4261
[tmax, N=1, LGBM]
    Métricas en train
        AP=0.390 | ROC_AUC=0.911
        prev=0.052 | P=0.357 | R=0.504 | F1=0.418 | acc=0.927
    Métricas en val
        AP=0.426 | ROC_AUC=0.881
        prev=0.081 | P=0.418 | R=0.521 | F1=0.464 | acc=0.902
    Métricas en test
        AP=0.572 | ROC_AUC=0.879
        prev=0.140 | P=0.484 | R=0.650 | F1=0.555 | acc=0.854
    Hecho en 475s | transcurrido 10.1 min | tiempo restante estimado ~110.8 min (55 modelos restantes)

[ 6/60] tmax N=3 Baseline
[tmax, N=3, Baseline]
    Métricas en train
        AP=0.184 | ROC_AUC=0.584
        prev=0.117 | P=0.451 | R=0.201 | F1=0.278 | acc=0.878
    Métricas en val
        AP=0.256 | ROC_AUC=0.601
        prev=0.168 | P=0.523 | R=0.248 | F1=0.337 | acc=0.836
    Métricas en test
        AP=0.390 | ROC_AUC=0.635
        prev=0.264 | P=0.635 | R=0.340 | F1=0.443 | acc=0.775
    Hecho en 1s | transcurrido 10.1 min | tiempo restante estimado ~90.8 min (54 modelos restantes)

[ 7/60] tmax N=3 NaiveBayes
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__var_smoothing=9.91564456663839e-07;, score=0.411 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.04033800832600378;, score=0.260 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.0007177141927992007;, score=0.393 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=6.155564318973005e-05;, score=0.413 total time=   0.3s
[CV 1/1] END classifier__var_smoothing=1.7707168643537813e-08;, score=0.408 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=1.7699302940633323e-08;, score=0.408 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=2.9152036385288267e-09;, score=0.408 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.008499808989182987;, score=0.299 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=6.440507553993706e-05;, score=0.413 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.0004619347374377367;, score=0.401 total time=   0.2s
    Búsqueda de 10 sobre 654784 filas en 1.8183 segundos | mejor AP en val: 0.4127
[tmax, N=3, NaiveBayes]
    Métricas en train
        AP=0.330 | ROC_AUC=0.767
        prev=0.117 | P=0.347 | R=0.409 | F1=0.376 | acc=0.842
    Métricas en val
        AP=0.413 | ROC_AUC=0.762
        prev=0.168 | P=0.379 | R=0.542 | F1=0.446 | acc=0.774
    Métricas en test
        AP=0.549 | ROC_AUC=0.774
        prev=0.264 | P=0.475 | R=0.668 | F1=0.555 | acc=0.718
    Hecho en 6s | transcurrido 10.2 min | tiempo restante estimado ~77.2 min (53 modelos restantes)

[ 8/60] tmax N=3 LogReg
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__C=0.005611516415334507;, score=0.413 total time=   1.5s
[CV 1/1] END .classifier__C=0.07969454818643935;, score=0.414 total time=   1.8s
[CV 1/1] END classifier__C=0.029106359131330698;, score=0.414 total time=   1.9s
[CV 1/1] END classifier__C=0.015751320499779727;, score=0.414 total time=   1.9s
[CV 1/1] END classifier__C=0.0020513382630874496;, score=0.413 total time=   1.3s
[CV 1/1] END classifier__C=0.002051110418843397;, score=0.413 total time=   1.5s
[CV 1/1] END classifier__C=0.0013066739238053278;, score=0.413 total time=   1.4s
[CV 1/1] END .classifier__C=0.05399484409787434;, score=0.414 total time=   2.1s
[CV 1/1] END classifier__C=0.015930522616241012;, score=0.414 total time=   1.8s
[CV 1/1] END classifier__C=0.026070247583707677;, score=0.414 total time=   1.9s
    Búsqueda de 10 sobre 654784 filas en 17.2479 segundos | mejor AP en val: 0.4139
[tmax, N=3, LogReg]
    Métricas en train
        AP=0.344 | ROC_AUC=0.780
        prev=0.117 | P=0.341 | R=0.474 | F1=0.396 | acc=0.832
    Métricas en val
        AP=0.414 | ROC_AUC=0.767
        prev=0.168 | P=0.366 | R=0.588 | F1=0.451 | acc=0.760
    Métricas en test
        AP=0.569 | ROC_AUC=0.784
        prev=0.264 | P=0.472 | R=0.707 | F1=0.566 | acc=0.714
    Hecho en 25s | transcurrido 10.6 min | tiempo restante estimado ~69.0 min (52 modelos restantes)

[ 9/60] tmax N=3 DecisionTree
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.386 total time=  11.4s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.403 total time=  10.4s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.392 total time=   4.9s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=sqrt, classifier__min_samples_leaf=100;, score=0.400 total time=   1.9s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=sqrt, classifier__min_samples_leaf=200;, score=0.403 total time=   2.0s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.401 total time=  10.8s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.394 total time=   5.6s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.392 total time=   4.9s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.401 total time=  12.4s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.406 total time=   8.8s
    Búsqueda de 10 sobre 654784 filas en 73.0949 segundos | mejor AP en val: 0.4060
[tmax, N=3, DecisionTree]
    Métricas en train
        AP=0.382 | ROC_AUC=0.800
        prev=0.117 | P=0.321 | R=0.565 | F1=0.409 | acc=0.810
    Métricas en val
        AP=0.406 | ROC_AUC=0.757
        prev=0.168 | P=0.368 | R=0.558 | F1=0.443 | acc=0.765
    Métricas en test
        AP=0.560 | ROC_AUC=0.770
        prev=0.264 | P=0.473 | R=0.661 | F1=0.551 | acc=0.716
    Hecho en 95s | transcurrido 12.2 min | tiempo restante estimado ~69.2 min (51 modelos restantes)

[10/60] tmax N=3 LGBM
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.430 total time=  34.5s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.428 total time=  33.7s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.425 total time=  38.9s
[CV 1/1] END classifier__bagging_fraction=0.5, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=1.0, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.426 total time=  45.7s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.411 total time=  36.8s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.377 total time=  25.9s
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=64;, score=0.326 total time=  22.6s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.410 total time=  38.3s
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.75, classifier__lambda_l1=0.5, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.311 total time=  24.7s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.75, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.419 total time=  36.9s
    Búsqueda de 10 sobre 654784 filas en 337.9672 segundos | mejor AP en val: 0.4304
[tmax, N=3, LGBM]
    Métricas en train
        AP=0.407 | ROC_AUC=0.820
        prev=0.117 | P=0.342 | R=0.573 | F1=0.428 | acc=0.822
    Métricas en val
        AP=0.430 | ROC_AUC=0.776
        prev=0.168 | P=0.389 | R=0.544 | F1=0.454 | acc=0.780
    Métricas en test
        AP=0.596 | ROC_AUC=0.794
        prev=0.264 | P=0.480 | R=0.704 | F1=0.571 | acc=0.721
    Hecho en 434s | transcurrido 19.4 min | tiempo restante estimado ~97.2 min (50 modelos restantes)

[11/60] tmax N=7 Baseline
[tmax, N=7, Baseline]
    Métricas en train
        AP=0.264 | ROC_AUC=0.550
        prev=0.221 | P=0.221 | R=1.000 | F1=0.363 | acc=0.221
    Métricas en val
        AP=0.358 | ROC_AUC=0.560
        prev=0.306 | P=0.306 | R=1.000 | F1=0.469 | acc=0.306
    Métricas en test
        AP=0.517 | ROC_AUC=0.590
        prev=0.440 | P=0.440 | R=1.000 | F1=0.611 | acc=0.440
    Hecho en 1s | transcurrido 19.5 min | tiempo restante estimado ~86.7 min (49 modelos restantes)

[12/60] tmax N=7 NaiveBayes
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__var_smoothing=9.91564456663839e-07;, score=0.487 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.04033800832600378;, score=0.370 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.0007177141927992007;, score=0.466 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=6.155564318973005e-05;, score=0.488 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=1.7707168643537813e-08;, score=0.486 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=1.7699302940633323e-08;, score=0.486 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=2.9152036385288267e-09;, score=0.485 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.008499808989182987;, score=0.406 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=6.440507553993706e-05;, score=0.488 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.0004619347374377367;, score=0.475 total time=   0.2s
    Búsqueda de 10 sobre 654520 filas en 1.9130 segundos | mejor AP en val: 0.4876
[tmax, N=7, NaiveBayes]
    Métricas en train
        AP=0.400 | ROC_AUC=0.691
        prev=0.221 | P=0.344 | R=0.601 | F1=0.438 | acc=0.658
    Métricas en val
        AP=0.488 | ROC_AUC=0.676
        prev=0.306 | P=0.389 | R=0.753 | F1=0.513 | acc=0.562
    Métricas en test
        AP=0.654 | ROC_AUC=0.713
        prev=0.440 | P=0.528 | R=0.847 | F1=0.650 | acc=0.599
    Hecho en 6s | transcurrido 19.6 min | tiempo restante estimado ~78.2 min (48 modelos restantes)

[13/60] tmax N=7 LogReg
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__C=0.005611516415334507;, score=0.490 total time=   1.5s
[CV 1/1] END .classifier__C=0.07969454818643935;, score=0.490 total time=   1.4s

## 4.2. CLM

### 4.2.1. Vista completa

In [27]:
res_clm_full = run_all_experiments(clm_df, "curated", clm_feats, "clm", verbose=True)

Ejecutando 60 experimentos (4 vars x 3 N x 5 modelos)
Número de iteraciones por modelo: {'NaiveBayes': 10, 'LogReg': 10, 'DecisionTree': 10, 'LGBM': 10} | jobs paralelos: 1

[ 1/60] tmax N=1 Baseline
[tmax, N=1, Baseline]
    Métricas en train
        AP=0.167 | ROC_AUC=0.658
        prev=0.060 | P=0.358 | R=0.357 | F1=0.358 | acc=0.923
    Métricas en val
        AP=0.361 | ROC_AUC=0.755
        prev=0.103 | P=0.563 | R=0.561 | F1=0.562 | acc=0.909
    Métricas en test
        AP=0.456 | ROC_AUC=0.780
        prev=0.162 | P=0.628 | R=0.631 | F1=0.630 | acc=0.880
    Hecho en 1s | transcurrido 0.0 min | tiempo restante estimado ~0.9 min (59 modelos restantes)

[ 2/60] tmax N=1 NaiveBayes
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__var_smoothing=9.91564456663839e-07;, score=0.400 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.04033800832600378;, score=0.200 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.0007177141927992007;, score=0.279 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=6.155564318973005e-05;, score=0.256 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=1.7707168643537813e-08;, score=0.475 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=1.7699302940633323e-08;, score=0.475 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=2.9152036385288267e-09;, score=0.472 total time=   0.3s
[CV 1/1] END classifier__var_smoothing=0.008499808989182987;, score=0.208 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=6.440507553993706e-05;, score=0.256 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.0004619347374377367;, score=0.297 total time=   0.2s
    Búsqueda de 10 sobre 203732 filas en 1.7878 segundos | mejor AP en val: 0.4750
[tmax, N=1, NaiveBayes]
    Métricas en train
        AP=0.311 | ROC_AUC=0.865
        prev=0.060 | P=0.212 | R=0.750 | F1=0.331 | acc=0.818
    Métricas en val
        AP=0.475 | ROC_AUC=0.872
        prev=0.103 | P=0.328 | R=0.786 | F1=0.463 | acc=0.812
    Métricas en test
        AP=0.627 | ROC_AUC=0.885
        prev=0.162 | P=0.451 | R=0.810 | F1=0.579 | acc=0.810
    Hecho en 6s | transcurrido 0.1 min | tiempo restante estimado ~3.2 min (58 modelos restantes)

[ 3/60] tmax N=1 LogReg
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__C=0.005611516415334507;, score=0.590 total time=   3.3s
[CV 1/1] END .classifier__C=0.07969454818643935;, score=0.596 total time=   4.4s
[CV 1/1] END classifier__C=0.029106359131330698;, score=0.595 total time=   3.5s
[CV 1/1] END classifier__C=0.015751320499779727;, score=0.594 total time=   3.3s
[CV 1/1] END classifier__C=0.0020513382630874496;, score=0.585 total time=   2.0s
[CV 1/1] END classifier__C=0.002051110418843397;, score=0.586 total time=   2.1s
[CV 1/1] END classifier__C=0.0013066739238053278;, score=0.584 total time=   2.2s
[CV 1/1] END .classifier__C=0.05399484409787434;, score=0.596 total time=   4.9s
[CV 1/1] END classifier__C=0.015930522616241012;, score=0.594 total time=   3.7s
[CV 1/1] END classifier__C=0.026070247583707677;, score=0.595 total time=   3.2s
    Búsqueda de 10 sobre 203732 filas en 32.6528 segundos | mejor AP en val: 0.5962
[tmax, N=1, LogReg]
    Métricas en train
        AP=0.393 | ROC_AUC=0.915
        prev=0.060 | P=0.418 | R=0.474 | F1=0.444 | acc=0.929
    Métricas en val
        AP=0.596 | ROC_AUC=0.925
        prev=0.103 | P=0.527 | R=0.674 | F1=0.592 | acc=0.904
    Métricas en test
        AP=0.701 | ROC_AUC=0.925
        prev=0.162 | P=0.620 | R=0.726 | F1=0.669 | acc=0.884
    Hecho en 90s | transcurrido 1.6 min | tiempo restante estimado ~30.5 min (57 modelos restantes)

[ 4/60] tmax N=1 DecisionTree
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.475 total time=  13.2s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.505 total time=  10.5s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.428 total time=   5.7s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=sqrt, classifier__min_samples_leaf=100;, score=0.464 total time=   1.1s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=sqrt, classifier__min_samples_leaf=200;, score=0.456 total time=   1.3s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.495 total time=  11.9s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.500 total time=   6.4s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.428 total time=   5.7s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.496 total time=  10.8s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.503 total time=   9.9s
    Búsqueda de 10 sobre 203732 filas en 76.5739 segundos | mejor AP en val: 0.5051
[tmax, N=1, DecisionTree]
    Métricas en train
        AP=0.499 | ROC_AUC=0.939
        prev=0.060 | P=0.368 | R=0.738 | F1=0.491 | acc=0.908
    Métricas en val
        AP=0.505 | ROC_AUC=0.897
        prev=0.103 | P=0.458 | R=0.676 | F1=0.546 | acc=0.884
    Métricas en test
        AP=0.642 | ROC_AUC=0.900
        prev=0.162 | P=0.535 | R=0.746 | F1=0.624 | acc=0.854
    Hecho en 104s | transcurrido 3.3 min | tiempo restante estimado ~46.9 min (56 modelos restantes)

[ 5/60] tmax N=1 LGBM
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.599 total time=  29.3s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.598 total time=  27.3s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.582 total time=  36.2s
[CV 1/1] END classifier__bagging_fraction=0.5, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=1.0, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.591 total time=  35.4s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.597 total time=  34.0s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.492 total time=  24.1s
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=64;, score=0.475 total time=  26.0s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.598 total time=  38.5s
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.75, classifier__lambda_l1=0.5, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.470 total time=  29.5s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.75, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.600 total time=  35.7s
    Búsqueda de 10 sobre 203732 filas en 316.0498 segundos | mejor AP en val: 0.5996
[tmax, N=1, LGBM]
    Métricas en train
        AP=0.630 | ROC_AUC=0.962
        prev=0.060 | P=0.467 | R=0.761 | F1=0.579 | acc=0.933
    Métricas en val
        AP=0.600 | ROC_AUC=0.931
        prev=0.103 | P=0.538 | R=0.682 | F1=0.601 | acc=0.906
    Métricas en test
        AP=0.723 | ROC_AUC=0.928
        prev=0.162 | P=0.598 | R=0.775 | F1=0.675 | acc=0.879
    Hecho en 407s | transcurrido 10.1 min | tiempo restante estimado ~111.4 min (55 modelos restantes)

[ 6/60] tmax N=3 Baseline
[tmax, N=3, Baseline]
    Métricas en train
        AP=0.208 | ROC_AUC=0.590
        prev=0.133 | P=0.479 | R=0.215 | F1=0.297 | acc=0.864
    Métricas en val
        AP=0.351 | ROC_AUC=0.656
        prev=0.187 | P=0.649 | R=0.355 | F1=0.459 | acc=0.843
    Métricas en test
        AP=0.467 | ROC_AUC=0.685
        prev=0.273 | P=0.722 | R=0.432 | F1=0.540 | acc=0.800
    Hecho en 1s | transcurrido 10.1 min | tiempo restante estimado ~91.3 min (54 modelos restantes)

[ 7/60] tmax N=3 NaiveBayes
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__var_smoothing=9.91564456663839e-07;, score=0.444 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.04033800832600378;, score=0.320 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.0007177141927992007;, score=0.390 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=6.155564318973005e-05;, score=0.345 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=1.7707168643537813e-08;, score=0.503 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=1.7699302940633323e-08;, score=0.503 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=2.9152036385288267e-09;, score=0.501 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.008499808989182987;, score=0.328 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=6.440507553993706e-05;, score=0.346 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.0004619347374377367;, score=0.401 total time=   0.2s
    Búsqueda de 10 sobre 203608 filas en 1.7063 segundos | mejor AP en val: 0.5031
[tmax, N=3, NaiveBayes]
    Métricas en train
        AP=0.376 | ROC_AUC=0.784
        prev=0.133 | P=0.332 | R=0.591 | F1=0.425 | acc=0.787
    Métricas en val
        AP=0.503 | ROC_AUC=0.785
        prev=0.187 | P=0.428 | R=0.639 | F1=0.513 | acc=0.773
    Métricas en test
        AP=0.648 | ROC_AUC=0.814
        prev=0.273 | P=0.560 | R=0.666 | F1=0.609 | acc=0.766
    Hecho en 5s | transcurrido 10.2 min | tiempo restante estimado ~77.4 min (53 modelos restantes)

[ 8/60] tmax N=3 LogReg
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__C=0.005611516415334507;, score=0.585 total time=   2.7s
[CV 1/1] END .classifier__C=0.07969454818643935;, score=0.587 total time=   5.7s
[CV 1/1] END classifier__C=0.029106359131330698;, score=0.587 total time=   4.2s
[CV 1/1] END classifier__C=0.015751320499779727;, score=0.587 total time=   3.2s
[CV 1/1] END classifier__C=0.0020513382630874496;, score=0.580 total time=   1.4s
[CV 1/1] END classifier__C=0.002051110418843397;, score=0.580 total time=   1.8s
[CV 1/1] END classifier__C=0.0013066739238053278;, score=0.577 total time=   1.5s
[CV 1/1] END .classifier__C=0.05399484409787434;, score=0.588 total time=   3.7s
[CV 1/1] END classifier__C=0.015930522616241012;, score=0.587 total time=   3.6s
[CV 1/1] END classifier__C=0.026070247583707677;, score=0.588 total time=   4.6s
    Búsqueda de 10 sobre 203608 filas en 32.4071 segundos | mejor AP en val: 0.5876
[tmax, N=3, LogReg]
    Métricas en train
        AP=0.454 | ROC_AUC=0.842
        prev=0.133 | P=0.467 | R=0.489 | F1=0.477 | acc=0.857
    Métricas en val
        AP=0.588 | ROC_AUC=0.841
        prev=0.187 | P=0.521 | R=0.616 | F1=0.565 | acc=0.822
    Métricas en test
        AP=0.707 | ROC_AUC=0.856
        prev=0.273 | P=0.621 | R=0.685 | F1=0.651 | acc=0.800
    Hecho en 91s | transcurrido 11.7 min | tiempo restante estimado ~76.3 min (52 modelos restantes)

[ 9/60] tmax N=3 DecisionTree
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.465 total time=  13.2s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.491 total time=  11.7s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.513 total time=   5.2s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=sqrt, classifier__min_samples_leaf=100;, score=0.468 total time=   1.2s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=sqrt, classifier__min_samples_leaf=200;, score=0.494 total time=   1.1s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.500 total time=  12.0s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.520 total time=   6.5s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.513 total time=   5.7s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.480 total time=  12.0s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.505 total time=  10.2s
    Búsqueda de 10 sobre 203608 filas en 78.6682 segundos | mejor AP en val: 0.5198
[tmax, N=3, DecisionTree]
    Métricas en train
        AP=0.431 | ROC_AUC=0.831
        prev=0.133 | P=0.403 | R=0.603 | F1=0.483 | acc=0.828
    Métricas en val
        AP=0.520 | ROC_AUC=0.820
        prev=0.187 | P=0.471 | R=0.655 | F1=0.548 | acc=0.798
    Métricas en test
        AP=0.631 | ROC_AUC=0.833
        prev=0.273 | P=0.592 | R=0.696 | F1=0.640 | acc=0.786
    Hecho en 96s | transcurrido 13.3 min | tiempo restante estimado ~75.6 min (51 modelos restantes)

[10/60] tmax N=3 LGBM
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.609 total time=  30.3s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.612 total time=  27.2s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.603 total time=  37.4s
[CV 1/1] END classifier__bagging_fraction=0.5, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=1.0, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.603 total time=  36.3s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.599 total time=  34.4s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.543 total time=  23.8s
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=64;, score=0.520 total time=  25.3s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.599 total time=  39.8s
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.75, classifier__lambda_l1=0.5, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.532 total time=  29.5s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.75, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.602 total time=  37.1s
    Búsqueda de 10 sobre 203608 filas en 321.1747 segundos | mejor AP en val: 0.6120
[tmax, N=3, LGBM]
    Métricas en train
        AP=0.673 | ROC_AUC=0.927
        prev=0.133 | P=0.558 | R=0.723 | F1=0.630 | acc=0.887
    Métricas en val
        AP=0.612 | ROC_AUC=0.851
        prev=0.187 | P=0.557 | R=0.605 | F1=0.580 | acc=0.836
    Métricas en test
        AP=0.721 | ROC_AUC=0.861
        prev=0.273 | P=0.660 | R=0.648 | F1=0.654 | acc=0.813
    Hecho en 392s | transcurrido 19.9 min | tiempo restante estimado ~99.4 min (50 modelos restantes)

[11/60] tmax N=7 Baseline
[tmax, N=7, Baseline]
    Métricas en train
        AP=0.299 | ROC_AUC=0.559
        prev=0.245 | P=0.245 | R=1.000 | F1=0.394 | acc=0.245
    Métricas en val
        AP=0.411 | ROC_AUC=0.595
        prev=0.317 | P=0.317 | R=1.000 | F1=0.482 | acc=0.317
    Métricas en test
        AP=0.550 | ROC_AUC=0.631
        prev=0.426 | P=0.426 | R=1.000 | F1=0.598 | acc=0.426
    Hecho en 1s | transcurrido 19.9 min | tiempo restante estimado ~88.6 min (49 modelos restantes)

[12/60] tmax N=7 NaiveBayes
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__var_smoothing=9.91564456663839e-07;, score=0.501 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.04033800832600378;, score=0.432 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.0007177141927992007;, score=0.483 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=6.155564318973005e-05;, score=0.449 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=1.7707168643537813e-08;, score=0.540 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=1.7699302940633323e-08;, score=0.540 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=2.9152036385288267e-09;, score=0.539 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.008499808989182987;, score=0.439 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=6.440507553993706e-05;, score=0.449 total time=   0.2s
[CV 1/1] END classifier__var_smoothing=0.0004619347374377367;, score=0.491 total time=   0.2s
    Búsqueda de 10 sobre 203360 filas en 1.7085 segundos | mejor AP en val: 0.5400
[tmax, N=7, NaiveBayes]
    Métricas en train
        AP=0.453 | ROC_AUC=0.702
        prev=0.245 | P=0.344 | R=0.734 | F1=0.468 | acc=0.591
    Métricas en val
        AP=0.540 | ROC_AUC=0.686
        prev=0.317 | P=0.406 | R=0.732 | F1=0.522 | acc=0.576
    Métricas en test
        AP=0.716 | ROC_AUC=0.758
        prev=0.426 | P=0.548 | R=0.839 | F1=0.663 | acc=0.636
    Hecho en 5s | transcurrido 20.0 min | tiempo restante estimado ~79.9 min (48 modelos restantes)

[13/60] tmax N=7 LogReg
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__C=0.005611516415334507;, score=0.587 total time=   2.6s
[CV 1/1] END .classifier__C=0.07969454818643935;, score=0.589 total time=   7.3s

### 4.2.2. Vista mínima

In [28]:
res_clm_min = run_all_experiments(clm_df, "minimal", clm_feats, "clm", verbose=True)

Ejecutando 60 experimentos (4 vars x 3 N x 5 modelos)
Número de iteraciones por modelo: {'NaiveBayes': 10, 'LogReg': 10, 'DecisionTree': 10, 'LGBM': 10} | jobs paralelos: 1

[ 1/60] tmax N=1 Baseline
[tmax, N=1, Baseline]
    Métricas en train
        AP=0.167 | ROC_AUC=0.658
        prev=0.060 | P=0.358 | R=0.357 | F1=0.358 | acc=0.923
    Métricas en val
        AP=0.361 | ROC_AUC=0.755
        prev=0.103 | P=0.563 | R=0.561 | F1=0.562 | acc=0.909
    Métricas en test
        AP=0.456 | ROC_AUC=0.780
        prev=0.162 | P=0.628 | R=0.631 | F1=0.630 | acc=0.880
    Hecho en 1s | transcurrido 0.0 min | tiempo restante estimado ~0.8 min (59 modelos restantes)

[ 2/60] tmax N=1 NaiveBayes
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__var_smoothing=9.91564456663839e-07;, score=0.533 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=0.04033800832600378;, score=0.319 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=0.0007177141927992007;, score=0.546 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=6.155564318973005e-05;, score=0.524 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=1.7707168643537813e-08;, score=0.528 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=1.7699302940633323e-08;, score=0.528 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=2.9152036385288267e-09;, score=0.528 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=0.008499808989182987;, score=0.525 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=6.440507553993706e-05;, score=0.524 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=0.0004619347374377367;, score=0.543 total time=   0.1s
    Búsqueda de 10 sobre 203732 filas en 0.6257 segundos | mejor AP en val: 0.5458
[tmax, N=1, NaiveBayes]
    Métricas en train
        AP=0.326 | ROC_AUC=0.897
        prev=0.060 | P=0.352 | R=0.436 | F1=0.390 | acc=0.918
    Métricas en val
        AP=0.546 | ROC_AUC=0.916
        prev=0.103 | P=0.486 | R=0.664 | F1=0.561 | acc=0.893
    Métricas en test
        AP=0.636 | ROC_AUC=0.907
        prev=0.162 | P=0.426 | R=0.895 | F1=0.577 | acc=0.788
    Hecho en 2s | transcurrido 0.1 min | tiempo restante estimado ~1.6 min (58 modelos restantes)

[ 3/60] tmax N=1 LogReg
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__C=0.005611516415334507;, score=0.577 total time=   1.3s
[CV 1/1] END .classifier__C=0.07969454818643935;, score=0.582 total time=   1.2s
[CV 1/1] END classifier__C=0.029106359131330698;, score=0.581 total time=   1.9s
[CV 1/1] END classifier__C=0.015751320499779727;, score=0.580 total time=   1.6s
[CV 1/1] END classifier__C=0.0020513382630874496;, score=0.574 total time=   1.0s
[CV 1/1] END classifier__C=0.002051110418843397;, score=0.574 total time=   1.2s
[CV 1/1] END classifier__C=0.0013066739238053278;, score=0.572 total time=   0.7s
[CV 1/1] END .classifier__C=0.05399484409787434;, score=0.582 total time=   1.1s
[CV 1/1] END classifier__C=0.015930522616241012;, score=0.580 total time=   1.6s
[CV 1/1] END classifier__C=0.026070247583707677;, score=0.581 total time=   1.6s
    Búsqueda de 10 sobre 203732 filas en 13.1224 segundos | mejor AP en val: 0.5818
[tmax, N=1, LogReg]
    Métricas en train
        AP=0.367 | ROC_AUC=0.907
        prev=0.060 | P=0.391 | R=0.476 | F1=0.430 | acc=0.924
    Métricas en val
        AP=0.582 | ROC_AUC=0.921
        prev=0.103 | P=0.510 | R=0.680 | F1=0.583 | acc=0.899
    Métricas en test
        AP=0.680 | ROC_AUC=0.920
        prev=0.162 | P=0.602 | R=0.728 | F1=0.659 | acc=0.878
    Hecho en 25s | transcurrido 0.5 min | tiempo restante estimado ~8.9 min (57 modelos restantes)

[ 4/60] tmax N=1 DecisionTree
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.476 total time=   3.1s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.530 total time=   2.8s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.496 total time=   1.5s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=sqrt, classifier__min_samples_leaf=100;, score=0.472 total time=   0.5s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=sqrt, classifier__min_samples_leaf=200;, score=0.530 total time=   0.5s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.489 total time=   2.9s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.506 total time=   1.7s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.497 total time=   1.5s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.518 total time=   2.8s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.518 total time=   2.6s
    Búsqueda de 10 sobre 203732 filas en 19.8392 segundos | mejor AP en val: 0.5303
[tmax, N=1, DecisionTree]
    Métricas en train
        AP=0.500 | ROC_AUC=0.934
        prev=0.060 | P=0.391 | R=0.637 | F1=0.485 | acc=0.919
    Métricas en val
        AP=0.530 | ROC_AUC=0.899
        prev=0.103 | P=0.483 | R=0.641 | F1=0.551 | acc=0.892
    Métricas en test
        AP=0.639 | ROC_AUC=0.897
        prev=0.162 | P=0.528 | R=0.703 | F1=0.603 | acc=0.850
    Hecho en 27s | transcurrido 0.9 min | tiempo restante estimado ~12.9 min (56 modelos restantes)

[ 5/60] tmax N=1 LGBM
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.603 total time=  12.8s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.605 total time=  12.4s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.596 total time=  14.8s
[CV 1/1] END classifier__bagging_fraction=0.5, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=1.0, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.598 total time=  18.1s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.601 total time=  13.3s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.496 total time=  10.5s
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=64;, score=0.462 total time=   8.6s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.599 total time=  14.2s
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.75, classifier__lambda_l1=0.5, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.481 total time=   9.4s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.75, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.600 total time=  12.7s
    Búsqueda de 10 sobre 203732 filas en 126.9995 segundos | mejor AP en val: 0.6051
[tmax, N=1, LGBM]
    Métricas en train
        AP=0.581 | ROC_AUC=0.952
        prev=0.060 | P=0.448 | R=0.690 | F1=0.543 | acc=0.930
    Métricas en val
        AP=0.605 | ROC_AUC=0.930
        prev=0.103 | P=0.537 | R=0.672 | F1=0.597 | acc=0.906
    Métricas en test
        AP=0.700 | ROC_AUC=0.922
        prev=0.162 | P=0.597 | R=0.743 | F1=0.662 | acc=0.877
    Hecho en 163s | transcurrido 3.6 min | tiempo restante estimado ~40.0 min (55 modelos restantes)

[ 6/60] tmax N=3 Baseline
[tmax, N=3, Baseline]
    Métricas en train
        AP=0.208 | ROC_AUC=0.590
        prev=0.133 | P=0.479 | R=0.215 | F1=0.297 | acc=0.864
    Métricas en val
        AP=0.351 | ROC_AUC=0.656
        prev=0.187 | P=0.649 | R=0.355 | F1=0.459 | acc=0.843
    Métricas en test
        AP=0.467 | ROC_AUC=0.685
        prev=0.273 | P=0.722 | R=0.432 | F1=0.540 | acc=0.800
    Hecho en 1s | transcurrido 3.7 min | tiempo restante estimado ~32.9 min (54 modelos restantes)

[ 7/60] tmax N=3 NaiveBayes
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__var_smoothing=9.91564456663839e-07;, score=0.554 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=0.04033800832600378;, score=0.509 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=0.0007177141927992007;, score=0.562 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=6.155564318973005e-05;, score=0.552 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=1.7707168643537813e-08;, score=0.550 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=1.7699302940633323e-08;, score=0.550 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=2.9152036385288267e-09;, score=0.550 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=0.008499808989182987;, score=0.559 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=6.440507553993706e-05;, score=0.552 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=0.0004619347374377367;, score=0.560 total time=   0.1s
    Búsqueda de 10 sobre 203608 filas en 0.6043 segundos | mejor AP en val: 0.5618
[tmax, N=3, NaiveBayes]
    Métricas en train
        AP=0.399 | ROC_AUC=0.814
        prev=0.133 | P=0.420 | R=0.484 | F1=0.450 | acc=0.842
    Métricas en val
        AP=0.562 | ROC_AUC=0.829
        prev=0.187 | P=0.497 | R=0.623 | F1=0.553 | acc=0.811
    Métricas en test
        AP=0.654 | ROC_AUC=0.833
        prev=0.273 | P=0.376 | R=0.957 | F1=0.540 | acc=0.556
    Hecho en 2s | transcurrido 3.7 min | tiempo restante estimado ~27.9 min (53 modelos restantes)

[ 8/60] tmax N=3 LogReg
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__C=0.005611516415334507;, score=0.572 total time=   1.4s
[CV 1/1] END .classifier__C=0.07969454818643935;, score=0.576 total time=   1.6s
[CV 1/1] END classifier__C=0.029106359131330698;, score=0.575 total time=   1.4s
[CV 1/1] END classifier__C=0.015751320499779727;, score=0.575 total time=   1.3s
[CV 1/1] END classifier__C=0.0020513382630874496;, score=0.567 total time=   1.0s
[CV 1/1] END classifier__C=0.002051110418843397;, score=0.567 total time=   1.1s
[CV 1/1] END classifier__C=0.0013066739238053278;, score=0.565 total time=   1.0s
[CV 1/1] END .classifier__C=0.05399484409787434;, score=0.576 total time=   1.4s
[CV 1/1] END classifier__C=0.015930522616241012;, score=0.575 total time=   1.6s
[CV 1/1] END classifier__C=0.026070247583707677;, score=0.575 total time=   1.5s
    Búsqueda de 10 sobre 203608 filas en 13.2641 segundos | mejor AP en val: 0.5760
[tmax, N=3, LogReg]
    Métricas en train
        AP=0.432 | ROC_AUC=0.828
        prev=0.133 | P=0.451 | R=0.475 | F1=0.463 | acc=0.853
    Métricas en val
        AP=0.576 | ROC_AUC=0.835
        prev=0.187 | P=0.511 | R=0.620 | F1=0.560 | acc=0.818
    Métricas en test
        AP=0.689 | ROC_AUC=0.846
        prev=0.273 | P=0.610 | R=0.669 | F1=0.638 | acc=0.793
    Hecho en 33s | transcurrido 4.2 min | tiempo restante estimado ~27.6 min (52 modelos restantes)

[ 9/60] tmax N=3 DecisionTree
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.455 total time=   3.2s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.499 total time=   3.1s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=100;, score=0.508 total time=   1.5s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=10, classifier__max_features=sqrt, classifier__min_samples_leaf=100;, score=0.505 total time=   0.6s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=sqrt, classifier__min_samples_leaf=200;, score=0.502 total time=   0.5s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.488 total time=   2.9s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.515 total time=   1.7s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=5, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.508 total time=   1.5s
[CV 1/1] END classifier__criterion=entropy, classifier__max_depth=15, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.490 total time=   2.6s
[CV 1/1] END classifier__criterion=gini, classifier__max_depth=10, classifier__max_features=None, classifier__min_samples_leaf=200;, score=0.499 total time=   2.6s
    Búsqueda de 10 sobre 203608 filas en 20.1676 segundos | mejor AP en val: 0.5154
[tmax, N=3, DecisionTree]
    Métricas en train
        AP=0.428 | ROC_AUC=0.829
        prev=0.133 | P=0.417 | R=0.549 | F1=0.474 | acc=0.837
    Métricas en val
        AP=0.515 | ROC_AUC=0.815
        prev=0.187 | P=0.503 | R=0.597 | F1=0.546 | acc=0.814
    Métricas en test
        AP=0.639 | ROC_AUC=0.832
        prev=0.273 | P=0.569 | R=0.688 | F1=0.623 | acc=0.773
    Hecho en 26s | transcurrido 4.7 min | tiempo restante estimado ~26.5 min (51 modelos restantes)

[10/60] tmax N=3 LGBM
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.587 total time=  12.8s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.587 total time=  11.8s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=1.0, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.568 total time=  15.6s
[CV 1/1] END classifier__bagging_fraction=0.5, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=1.0, classifier__learning_rate=0.01, classifier__num_leaves=64;, score=0.571 total time=  17.2s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.571 total time=  13.5s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.5, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.477 total time=  10.2s
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.5, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=64;, score=0.457 total time=   8.7s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=1.0, classifier__lambda_l1=0.5, classifier__lambda_l2=0.5, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.577 total time=  14.2s
[CV 1/1] END classifier__bagging_fraction=1.0, classifier__feature_fraction=0.75, classifier__lambda_l1=0.5, classifier__lambda_l2=0.0, classifier__learning_rate=0.1, classifier__num_leaves=32;, score=0.471 total time=   9.5s
[CV 1/1] END classifier__bagging_fraction=0.75, classifier__feature_fraction=0.75, classifier__lambda_l1=0.0, classifier__lambda_l2=0.0, classifier__learning_rate=0.01, classifier__num_leaves=32;, score=0.583 total time=  12.6s
    Búsqueda de 10 sobre 203608 filas en 126.0821 segundos | mejor AP en val: 0.5866
[tmax, N=3, LGBM]
    Métricas en train
        AP=0.644 | ROC_AUC=0.917
        prev=0.133 | P=0.524 | R=0.724 | F1=0.608 | acc=0.875
    Métricas en val
        AP=0.587 | ROC_AUC=0.837
        prev=0.187 | P=0.540 | R=0.587 | F1=0.562 | acc=0.829
    Métricas en test
        AP=0.695 | ROC_AUC=0.852
        prev=0.273 | P=0.633 | R=0.663 | F1=0.647 | acc=0.803
    Hecho en 162s | transcurrido 7.4 min | tiempo restante estimado ~36.9 min (50 modelos restantes)

[11/60] tmax N=7 Baseline
[tmax, N=7, Baseline]
    Métricas en train
        AP=0.299 | ROC_AUC=0.559
        prev=0.245 | P=0.245 | R=1.000 | F1=0.394 | acc=0.245
    Métricas en val
        AP=0.411 | ROC_AUC=0.595
        prev=0.317 | P=0.317 | R=1.000 | F1=0.482 | acc=0.317
    Métricas en test
        AP=0.550 | ROC_AUC=0.631
        prev=0.426 | P=0.426 | R=1.000 | F1=0.598 | acc=0.426
    Hecho en 1s | transcurrido 7.4 min | tiempo restante estimado ~32.9 min (49 modelos restantes)

[12/60] tmax N=7 NaiveBayes
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__var_smoothing=9.91564456663839e-07;, score=0.570 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=0.04033800832600378;, score=0.480 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=0.0007177141927992007;, score=0.580 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=6.155564318973005e-05;, score=0.575 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=1.7707168643537813e-08;, score=0.568 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=1.7699302940633323e-08;, score=0.568 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=2.9152036385288267e-09;, score=0.568 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=0.008499808989182987;, score=0.559 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=6.440507553993706e-05;, score=0.575 total time=   0.1s
[CV 1/1] END classifier__var_smoothing=0.0004619347374377367;, score=0.579 total time=   0.1s
    Búsqueda de 10 sobre 203360 filas en 0.6032 segundos | mejor AP en val: 0.5798
[tmax, N=7, NaiveBayes]
    Métricas en train
        AP=0.474 | ROC_AUC=0.725
        prev=0.245 | P=0.434 | R=0.573 | F1=0.494 | acc=0.712
    Métricas en val
        AP=0.580 | ROC_AUC=0.712
        prev=0.317 | P=0.463 | R=0.640 | F1=0.538 | acc=0.651
    Métricas en test
        AP=0.719 | ROC_AUC=0.767
        prev=0.426 | P=0.436 | R=0.991 | F1=0.605 | acc=0.449
    Hecho en 2s | transcurrido 7.4 min | tiempo restante estimado ~29.7 min (48 modelos restantes)

[13/60] tmax N=7 LogReg
Fitting 1 folds for each of 10 candidates, totalling 10 fits
[CV 1/1] END classifier__C=0.005611516415334507;, score=0.574 total time=   0.9s
[CV 1/1] END .classifier__C=0.07969454818643935;, score=0.575 total time=   1.4s